# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
inhibit_all_warnings!
target 'tetris-online' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'
  pod 'XCGLogger'

  # Pods for tetris-online

  target 'tetris-onlineTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tetris-onlineUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
